### PR TITLE
Fixes bug with edgelabel visibility toggle

### PR DESCRIPTION
**Pull request by haakon-gun**

### CODE REVIEW

**Comment by haakon-gun** [comment]
closes #217

**Comment by AndreasWintherMoen** [comment]
I made drawEdgeLabels a separate function so that we avoid using a nullable boolean as toggle. Think this is a cleaner solution. 

@erikskaar any updates on the cypress tests? I don't think we can merge before these are fixed.

**Comment by haakon-gun** [comment]
Works for me! :)

**Review by AndreasWintherMoen — APPROVED** [review]
LGTM if we can fix Cypress errors.

**Pull request merged**
